name: Build with Hugo

on:
  push:
    branches:
      - convert
      - gitbook-sync
      - gitbook-node-sync
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout DCS Docs
        uses: actions/checkout@v2
        with:
          ref: gitbook-sync
          path: gitbook/dcs

      - name: Checkout Node Docs
        uses: actions/checkout@v2
        with:
          ref: gitbook-node-sync
          path: gitbook/node

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Convert Pages
        run: make convert-ci

      - name: Run Hugo
        run: make build

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: docs.storj.io